In [1]:
# Importing the required libraries

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
# Read the csv file using 'read_csv'. Please write your dataset location here.

wine = pd.DataFrame(pd.read_csv("C:/PATH/MACHINE_LEARNING/USE_CASES/Wine Reviews/winemag-data-130k-v2.csv"))

wine.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [13]:
wine.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 13 columns):
country                  129908 non-null object
description              129971 non-null object
designation              92506 non-null object
points                   129971 non-null int64
price                    120975 non-null float64
province                 129908 non-null object
region_1                 108724 non-null object
region_2                 50511 non-null object
taster_name              103727 non-null object
taster_twitter_handle    98758 non-null object
title                    129971 non-null object
variety                  129970 non-null object
winery                   129971 non-null object
dtypes: float64(1), int64(1), object(11)
memory usage: 12.9+ MB

In [158]:
##Remove Duplicates From Dataframe

wine_dedup = wine.drop_duplicates()
wine_dedup.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119988 entries, 0 to 129970
Data columns (total 13 columns):
country                  119929 non-null object
description              119988 non-null object
designation              85443 non-null object
points                   119988 non-null int64
price                    111593 non-null float64
province                 119929 non-null object
region_1                 100428 non-null object
region_2                 46769 non-null object
taster_name              95071 non-null object
taster_twitter_handle    90542 non-null object
title                    119988 non-null object
variety                  119987 non-null object
winery                   119988 non-null object
dtypes: float64(1), int64(1), object(11)
memory usage: 12.8+ MB

<font color = blue> 
As there are ~63 recs where country is Blank..And all winery have non blank values..A winery should not be in multiple countries; if the data is correct then impute same coutry for the same winery accross where country is Blank </font>

In [26]:
df = wine_dedup.groupby(['winery'])['country'].nunique()

In [30]:
df.to_csv('C:/PATH/MACHINE_LEARNING/USE_CASES/Wine Reviews/test.csv', index=False, mode='a',header=False)

In [118]:
##List of winery for which the country name is blank
lst = ['Amiran Vepkhvadze',
'BÃ¼yÃ¼lÃ¼baÄŸ',
'Bachelder',
'Bartho Eksteen',
'Barton & Guestier',
'Chilcas',
'El Capricho',
'Familia Deicas',
'Gotsa Family Wines',
'Kakhetia Traditional Winemaking',
'Ktima Voyatzi',
'Les FrÃ¨res Dutruy',
'Lismore',
'Logodaj',
'Mt. Beautiful',
'Neumeister',
'Newton Johnson',
'Orbelus',
'Psagot',
'Ross-idi',
'Santa Ema',
'SomlÃ³i VÃ¡ndor',
'St. Donat',
'Stone Castle',
'Teliani Valley',
'Tsililis',
'Undurraga']


## Print countries for the above winery

for i in range(len(lst)):
    ##print(lst[i])
    X_few = wine_dedup[wine_dedup['winery'] == lst[i]]['country'].values
    X_fews = wine_dedup[wine_dedup['winery'] == lst[i]]['winery'].values
    print(X_few,np.unique(X_fews))
    print('\n-------------------\n')

[nan] ['Amiran Vepkhvadze']

-------------------

[] []

-------------------

['Canada' nan] ['Bachelder']

-------------------

[nan 'South Africa'] ['Bartho Eksteen']

-------------------

['France' nan 'France' 'France' 'France' 'France' 'France' 'France'
 'France' nan 'France' 'France' 'France' 'France' 'France' 'France'
 'France' 'France' 'France' 'France' 'France' 'France' 'France' 'France'
 'France' 'France' 'France' 'France' 'France' 'France' 'France' 'France'
 'France' 'France' 'France' 'France' 'France' 'France' 'France' 'France'
 'France' 'France' 'France' 'France' 'France' 'France' 'France' 'France'
 'France' 'France' 'France' 'France' 'France' 'France' 'France' 'France'
 'France' 'France' 'France' 'France' 'France' 'France' 'France' 'France'
 'France' 'France' 'France' 'France' 'France' 'France' 'France' 'France'
 'France' 'France' 'France' 'France' 'France' 'France' 'France' 'France'] ['Barton & Guestier']

-------------------

['Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' nan
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'] ['Chilcas']

-------------------

[nan nan nan] ['El Capricho']

-------------------

['Uruguay' 'Uruguay' 'Uruguay' nan 'Uruguay' 'Uruguay' 'Uruguay' 'Uruguay'
 'Uruguay' 'Uruguay' 'Uruguay' 'Uruguay' 'Uruguay'] ['Familia Deicas']

-------------------

[nan nan nan 'Georgia' nan] ['Gotsa Family Wines']

-------------------

[nan] ['Kakhetia Traditional Winemaking']

-------------------

[nan 'Greece' nan 'Greece'] ['Ktima Voyatzi']

-------------------

[] []

-------------------

[nan] ['Lismore']

-------------------

['Bulgaria' nan] ['Logodaj']

-------------------

['New Zealand' nan 'New Zealand' 'New Zealand' 'New Zealand' nan
 'New Zealand'] ['Mt. Beautiful']

-------------------

['Austria' 'Austria' 'Austria' 'Austria' 'Austria' nan 'Austria' nan nan
 'Austria' 'Austria' 'Austria' 'Austria' 'Austria' 'Austria' 'Austria' nan
 'Austria' 'Austria' 'Austria' 'Austria' 'Austria' 'Austria' nan 'Austria'
 'Austria' nan nan nan 'Austria' 'Austria' 'Austria' 'Austria' 'Austria'
 'Austria' nan 'Austria' 'Austria'] ['Neumeister']

-------------------

['South Africa' nan] ['Newton Johnson']

-------------------

[nan nan nan nan nan nan nan] ['Orbelus']

-------------------

['Israel' 'Israel' 'Israel' 'Israel' 'Israel' 'Israel' 'Israel' 'Israel'
 nan 'Israel' 'Israel' 'Israel' nan 'Israel' 'Israel' nan 'Israel'
 'Israel' nan] ['Psagot']

-------------------

[nan nan nan nan] ['Ross-idi']

-------------------

['Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' nan 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile'] ['Santa Ema']

-------------------

[] []

-------------------

[nan nan nan] ['St. Donat']

-------------------

[nan nan nan nan] ['Stone Castle']

-------------------

['Georgia' nan 'Georgia' 'Georgia' 'Georgia' 'Georgia' 'Georgia'] ['Teliani Valley']

-------------------

[nan nan nan] ['Tsililis']

-------------------

['Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' nan 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'
 'Chile' 'Chile' 'Chile' 'Chile' 'Chile'] ['Undurraga']

-------------------

<font color = blue> 
From above -- country can be replaced with same coutry for a particular winery, whereever country is null
    
However a winery(name) can have multiple countries
</font>

In [143]:
##wine_null_country_winery = wine[wine.country.isnull()]['winery']
##wine_null_country_winery

wine_null_country_winery = wine_dedup.loc[wine['winery'].isin(lst)][['country','winery']]
wine_null_country_winery_dedup = wine_null_country_winery.drop_duplicates()
##wine_null_country_winery_dedup

In [144]:
notnull_country_winery = wine_null_country_winery_dedup.dropna(subset=['country'])
notnull_country_winery.sort_values(by=['winery'],ascending = True)

             country              winery
13062         Canada           Bachelder
34853   South Africa      Bartho Eksteen
2789          France   Barton & Guestier
7132           Chile             Chilcas
9133         Uruguay      Familia Deicas
110970       Georgia  Gotsa Family Wines
112132        Greece       Ktima Voyatzi
68333       Bulgaria             Logodaj
3322     New Zealand       Mt. Beautiful
5493         Austria          Neumeister
34869   South Africa      Newton Johnson
6122          Israel              Psagot
967            Chile           Santa Ema
14756        Georgia      Teliani Valley
394            Chile           Undurraga

In [155]:
nn = notnull_country_winery.to_numpy()
for i in nn:
    country = i[0]
    winery = i[1]
    ##df['Cat1'].fillna(df['Cat2'])
    print(country)
    print(winery)

Chile
Undurraga
Chile
Santa Ema
France
Barton & Guestier
New Zealand
Mt. Beautiful
Austria
Neumeister
Israel
Psagot
Chile
Chilcas
Uruguay
Familia Deicas
Canada
Bachelder
Georgia
Teliani Valley
South Africa
Bartho Eksteen
South Africa
Newton Johnson
Bulgaria
Logodaj
Georgia
Gotsa Family Wines
Greece
Ktima Voyatzi